#!/usr/bin/bash
export OMP_NUM_THREADS=1

for SEED in 2020 2021 2022
do
  torchrun --nproc_per_node=8 experiment.py \
      --batch_size 50 \
      --path /dataQ/tommie_kerssies \
      --method cotta \
      --seed ${SEED} \
      --epochs 1 \
      --model best_1_${SEED}.pth.tar \
      --sources 1 \
      --targets 2 3 4 5 6 7 8 9 10 11 \
      --dataset CORe50 \
      --lr 1e-3 \
      --rst_m 0.01 \
      --mt_alpha 0.9
done