#!/usr/bin/bash
torchrun --nproc_per_node=5 train.py --batch_size 1024 --max_epochs 10 --train_sessions 1 2 4 5 6 8 9 11
torchrun --nproc_per_node=5 train.py --batch_size 1024 --max_epochs 10 --train_sessions 1 2 3 5 6 7 8 9
torchrun --nproc_per_node=5 train.py --batch_size 1024 --max_epochs 10 --train_sessions 1 2 3 4 5 6 7 8 9 10
torchrun --nproc_per_node=5 train.py --batch_size 1024 --max_epochs 10 --train_sessions 1 2 3 4 5 6 7 8 9 11
torchrun --nproc_per_node=5 train.py --batch_size 1024 --max_epochs 10 --train_sessions 1
